<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Bez Dph' => '',
    'Datum Platby' => '',
    'Datum ZP' => '',
    'Detail platby' => '',
    'Detaily Platby' => '',
    'Dph' => '',
    'Editing' => '',
    'Faktury' => '',
    'Firmy' => '',
    'ID' => '',
    'Jméno plátce' => '',
    'Název právnické osoby' => '',
    'Odstranit' => '',
    'Opravdu chcete odstranit?' => '',
    'Plátce' => '',
    'Poznámka' => '',
    'Přidat Detail Platby' => '',
    'Přidat Firmu' => '',
    'Přidat Plátce' => '',
    'Přidat Způsob Platby' => '',
    'Přidat Způsoby Platby' => '',
    'Přidat další' => '',
    'Přidat fakturu' => '',
    'Přidat firmu' => '',
    'Reset' => '',
    'Search' => '',
    'Společnost' => '',
    'The requested page does not exist.' => '',
    'Uložit' => '',
    'Upravit' => '',
    'Upravit Detail Platby: {nameAttribute}' => '',
    'Upravit Fakturu: {nameAttribute}' => '',
    'Upravit Firmu: {nameAttribute}' => '',
    'Upravit Plátce: {nameAttribute}' => '',
    'Upravit Způsob Platby: {nameAttribute}' => '',
    'Vč Dph' => '',
    'Změnit' => '',
    'Způsob Platby' => '',
    'Způsob platby' => '',
    'Způsoby Platby' => '',
];
